<a href="https://colab.research.google.com/github/cl1nch/PY-TUT-2026/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/OWL-ML/IBFW-PY-2026-Tutorial/blob/main/numpy_basics.ipynb)

*(Tip: Ctrl/Cmd + click to open in a new tab)*


# NumPy (Numerical Python)

NumPy (Numerical Python) ist eine leistungsstarke Bibliothek, die für schnelle und effiziente numerische Berechnungen entwickelt wurde. Sie wird häufig in Bereichen wie Datenanalyse, maschinellem Lernen, wissenschaftlichem Rechnen und Ingenieurwesen eingesetzt und ist damit ein unverzichtbares Werkzeug für alle, die mit Daten in Python arbeiten. Im Zentrum des NumPy-Pakets steht das ndarray-Objekt. Dieses kapselt n-dimensionale Arrays homogener Datentypen, wobei viele Operationen aus Leistungsgründen in kompiliertem Code ausgeführt werden.

Es kann in Python-Code wie folgt importiert werden: `import numpy as np`

Diese weit verbreitete Konvention ermöglicht den Zugriff auf NumPy-Funktionen mit einem kurzen, leicht erkennbaren Präfix (np.), während gleichzeitig NumPy-Funktionen von anderen mit demselben Namen unterschieden werden.

---

*NumPy (Numerical Python) is a powerful library designed for fast and efficient numerical computation. It is widely used in areas such as data analysis, machine learning, scientific computing, and engineering, making it an essential tool for anyone working with data in Python. At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance.*

*It may be imported into Python code like:* `import numpy as np`

*This widespread convention allows access to NumPy features with a short, recognizable prefix (np.) while distinguishing NumPy features from others that have the same name.*

In [1]:
import numpy as np

# Multi-Dimensional Array

Das Hauptobjekt von NumPy ist das homogene mehrdimensionale Array. Es ist eine Tabelle von Elementen (meist Zahlen), die alle denselben Datentyp haben und durch ein Tupel nichtnegativer Ganzzahlen indiziert werden. In NumPy werden Dimensionen als Achsen bezeichnet.

---

*NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.*

In [2]:
one_d_arr = np.array([1,2,1])
print(one_d_arr)
print(type(one_d_arr))

[1 2 1]
<class 'numpy.ndarray'>


Im obigen Beispiel stellt `one_d_arr` die Koordinaten eines Punktes im 3D-Raum dar, `[1, 2, 1]`, und hat eine Achse. Diese Achse enthält 3 Elemente, daher sagen wir, dass sie eine Länge von 3 hat.

---

*In the above example, the `one_d_arr` provides the coordinates of a point in 3D space, `[1, 2, 1]`, has one axis. That axis has 3 elements in it, so we say it has a length of 3.*

In [3]:
two_d_array = np.array([[1, 2, 3],
                         [4, 5, 6]])
print(two_d_array)

[[1 2 3]
 [4 5 6]]


Im obigen Beispiel hat `two_d_array` 2 Achsen. Die erste Achse hat eine Länge von 2, da wir zwei enthaltene Arrays haben; die zweite Achse hat eine Länge von 3, da jedes Array 3 Elemente enthält.

---

*In the example above, the `two_d_array` has 2 axes. The first axis has a length of 2 as we have two constituent arrays, the second axis has a length of 3 as each array has 3 elements.*

### Häufige Eigenschaften von NumPy-Arrays / *Common Properties of NumPy Arrays*

| Eigenschaft | Beschreibung                             | Beispielcode           | Ausgabe  |
| ----------- | ---------------------------------------- | ---------------------- | -------- |
| `shape`     | Dimensionen des Arrays (Zeilen, Spalten) | `two_d_array.shape`    | `(2, 3)` |
| `ndim`      | Anzahl der Dimensionen                   | `two_d_array.ndim`     | `2`      |
| `size`      | Gesamtanzahl der Elemente                | `two_d_array.size`     | `6`      |
| `dtype`     | Datentyp der Elemente                    | `two_d_array.dtype`    | `int64`  |
| `itemsize`  | Größe jedes Elements (Bytes)             | `two_d_array.itemsize` | `8`      |
| `nbytes`    | Insgesamt verwendeter Speicher (Bytes)   | `two_d_array.nbytes`   | `48`     |


---

| Property   | Description                         | Example Code           | Output   |
| ---------- | ----------------------------------- | ---------------------- | -------- |
| `shape`    | Dimensions of array (rows, columns) | `two_d_array.shape`    | `(2, 3)` |
| `ndim`     | Number of dimensions                | `two_d_array.ndim`     | `2`      |
| `size`     | Total number of elements            | `two_d_array.size`     | `6`      |
| `dtype`    | Data type of elements               | `two_d_array.dtype`    | `int64`  |
| `itemsize` | Size of each element (bytes)        | `two_d_array.itemsize` | `8`      |
| `nbytes`   | Total memory used (bytes)           | `two_d_array.nbytes`   | `48`     |


In [4]:
# 2D array: gives number of axes
print(f"Dimensions: {two_d_array.ndim}")

# 2 rows, 3 columns: size along each axis
print(f"Shape: {two_d_array.shape}")

# total elements
print(f"Size: {two_d_array.size}")

# data type
print(f"Datatype: {two_d_array.dtype}")

Dimensions: 2
Shape: (2, 3)
Size: 6
Datatype: int64


3D-Arrays können als ein Stapel von 2D-Arrays angezeigt werden.

---

*3D arrays can be shown as a stack of 2D arrays.*

In [5]:
# lets create a 3D array
array_3d = np.array([
    [[1,2], [3,4]],
    [[5,6], [7,8]]
])

In [7]:
print(array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


```
[1, 2, 3]             → 1 level  → ndim = 1  
[[1,2],[3,4]]         → 2 levels → ndim = 2  
[[[1],[2]],[[3],[4]]] → 3 levels → ndim = 3  
```

# Verschiedene Möglichkeiten, Arrays zu erstellen / *Different Ways to Create Arrays*

Wie wir bereits gesehen haben, können wir einen Array aus einer normalen Python-Liste oder einem Tupel mithilfe der Funktion array erstellen. Der Typ des resultierenden Arrays wird aus dem Typ der Elemente in den Sequenzen abgeleitet.

---

*As we have already seen, you can create an array from a regular Python list or tuple using the `array` function. The type of the resulting array is deduced from the type of the elements in the sequences.*

In [28]:
a = np.array([2, 3, 4])
print(f"Data type of first array: {a.dtype}")
b = np.array((1.2, 3.5, 5.1))
print(f"Data type of second array: {b.dtype}")

Data type of first array: int64
Data type of second array: float64


In [29]:
# however the following is wrong, array() only accept a sequence
a = np.array(1, 2, 3, 4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

Der Typ des Arrays kann auch bei der Erstellung explizit angegeben werden:

---

*The type of the array can also be explicitly specified at creation time:*

In [16]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)
print(c.dtype)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128


Um Zahlenfolgen zu erstellen, stellt NumPy die Funktion `arange` zur Verfügung, die analog zur in Python eingebauten Funktion range ist, jedoch ein Array zurückgibt.

`np.arange(start, stop, step)`

---

*To create sequences of numbers, NumPy provides the `arange` function which is analogous to the Python built-in `range`, but returns an array.*

`np.arange(start, stop, step)`

In [17]:
a = np.arange(15)

print(a)
print(type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


In [18]:
print(f"Dimensions: {a.ndim}")
print(f"Shape: {a.shape}")

Dimensions: 1
Shape: (15,)


In [19]:
a = np.arange(10)**3
# every item 1 to 10 gets cubed.
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [20]:
b = np.arange(10, 30, 5)
print(b)

[10 15 20 25]


In [ ]:
c = np.arange(0, 2, 0.3)  # it accepts float arguments

print(c)

Wenn arange mit Fließkomma-Argumenten verwendet wird, ist es aufgrund der begrenzten Genauigkeit von Fließkommazahlen im Allgemeinen nicht möglich, die Anzahl der erhaltenen Elemente vorherzusagen. Aus diesem Grund ist es meist besser, die Funktion linspace zu verwenden, die als Argument die gewünschte Anzahl an Elementen erhält, anstatt des Schritts:

```
np.linspace(start, stop, num)
```

---

*When `arange` is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function `linspace` that receives as an argument the number of elements that we want, instead of the step:*

```
np.linspace(start, stop, num)
```

In [23]:
linespace_array = np.linspace(0, 2, 9) # 9 numbers from 0 to 2

print(linespace_array)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [24]:
x = np.linspace(0, 2 * np.pi, 9)        # useful to evaluate function at lots of points
print(x)
f = np.sin(x)
print(f)

[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]
[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]


Oft sind die Elemente eines Arrays ursprünglich unbekannt, aber seine Größe ist bekannt. Daher bietet NumPy mehrere Funktionen, um Arrays mit anfänglichem Platzhalterinhalt zu erstellen. Diese minimieren die Notwendigkeit, Arrays zu vergrößern, was eine teure Operation ist.

Die Funktion `zeros` erstellt ein Array voller Nullen, die Funktion `ones` erstellt ein Array voller Einsen, und die Funktion `empty` erstellt ein Array, dessen anfänglicher Inhalt zufällig ist und vom Speicherzustand abhängt. Standardmäßig ist der `dtype` des erstellten Arrays `float64`, kann aber über das Schlüsselwortargument `dtype` angegeben werden.

---

*Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.*

*The function `zeros` creates an array full of zeros, the function `ones` creates an array full of ones, and the function `empty` creates an array whose initial content is random and depends on the state of the memory. By default, the `dtype` of the created array is `float64`, but it can be specified via the key word argument `dtype`.*

In [25]:
array_with_zeros = np.zeros((3, 4))

print(array_with_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
array_with_ones = np.ones((2, 3, 4), dtype=np.int16)

print(array_with_ones)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [27]:
empty_array = np.empty((2, 3))

print(empty_array)

[[3.60141412e-315 0.00000000e+000 6.87047448e-310]
 [6.87047448e-310 3.60051375e-315 6.87047448e-310]]


Wir können auch ein Array mit Zufallszahlen erstellen. random.rand erstellt ein Array der angegebenen Form und füllt es mit Zufallswerten aus einer gleichmäßigen Verteilung über $[0, 1)$.

---

*We can also create an array of random numbers. `random.rand` creates an array of the given shape and populate it with random samples from a uniform distribution over $[0, 1)$.*

In [ ]:
cube = np.random.rand(2, 2, 1)
print(cube)

### Aufgabe / *Exercise:*

Für jedes der folgenden Beispiele: Gib das Array, die Dimensionen, die Form, die Größe und den Datentyp des Arrays aus:
* Erstelle ein 1D-Array mit 10 gleichmäßig verteilten Werten zwischen 5 und 50.
* Wandle eine Python-Liste `[1, 2, 3, 4, 5]` in ein NumPy-Array um.
* Erstelle eine $3\times3$-Einheitsmatrix.
* Erstelle eine 3×2-Matrix mit Zufallszahlen.

---

For each of the following, print the array, dimensions, shape, size and the data type of the array:
1. Create a 1D array of 10 evenly spaced values between 5 and 50.
2. Convert a Python list `[1, 2, 3, 4, 5]` into a NumPy array.
3. Create a $3\times3$ identity matrix.
4. Create a 3×2 matrix with random numbers.

In [45]:
#1
linespace_array = np.linspace(5, 50, 10)
print(linespace_array)

#2
l1 = [1, 2, 3, 4, 5]
np_l1 = np.array(l1)
print(np_l1)

#3
np1 =np.identity(3)
print (np1)

#4
nprandom = np.random.rand(3,2)
print(nprandom)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
[1 2 3 4 5]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.82792806 0.81246786]
 [0.31516915 0.24605278]
 [0.15519015 0.43424259]]


# Numpy Array Indexing

Wie eine Python-Liste ist ein 1D-NumPy-Array eine Folge von Werten, deren Indizes bei 0 beginnen. Auf Elemente wird zugegriffen, indem diese Indizes in eckigen Klammern verwendet werden, z. B. `one_d_arr[0]` für das erste Element. Negative Indizes zählen vom Ende, sodass `one_d_arr[-1]` das letzte Element liefert.

---

Like a python list, a 1D NumPy array is a sequence of values with indices starting at 0. We access elements by using these indices in square brackets like `one_d_arr[0]` for the first element. Negative indices count from the end so `one_d_arr[-1]` gives the last element.

In [46]:
print(one_d_arr)
print(f"First element: {one_d_arr[0]}")
print(f"Last element: {one_d_arr[-1]}")

[1 2 1]
First element: 1
Last element: 1


Bei 2D-Arrays können wir auf Elemente zugreifen, indem wir sowohl Zeilen- als auch Spaltenindizes angeben, z. B. `two_d_array[row, column]`.

---

*For 2D arrays, we can access elements by specifying both row and column indices like `two_d_array[row, column]`.*

In [48]:
print(two_d_array)

print(two_d_array[1, 2])

[[1 2 3]
 [4 5 6]]
6


`two_d_array[1, 2]` greift auf das Element in der zweiten Zeile (Index 1) und der dritten Spalte (Index 2) zu, das den Wert 6 hat.

Wie bereits erwähnt, können 3D-Arrays als Stapel von 2D-Arrays visualisiert werden. Hierfür werden drei Indizes benötigt:
* Tiefe: Gibt die 2D-Schicht an.
* Zeile: Gibt die Zeile innerhalb der Schicht an.
* Spalte: Gibt die Spalte innerhalb der Zeile an.

---

`two_d_array[1, 2]` *accesses the element in the second row (index 1) and third column (index 2) which is 6.*

*As mentioned before, 3D arrays can be visualized as a stack of 2D arrays, we need three indices:*
- *Depth: Specifies the 2D slice.*
- *Row: Specifies the row within the slice.*
- *Column: Specifies the column within the row.*

In [49]:
print(array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [50]:
print(array_3d[1, 1, 0])

7


#### Boolean Indexing

Es ermöglicht uns, Elemente aus einem Array basierend auf einer Bedingung zu filtern und gibt nur diejenigen zurück, die diese erfüllen. Wir erstellen ein Boolesches Array aus einer Bedingung und verwenden es, um Elemente auszuwählen, und können Bedingungen mit logischen Operatoren kombinieren.

Wir können auch logische Operatoren wie & (UND), | (ODER) und ~ (NICHT) verwenden, um Bedingungen zu kombinieren.

---

*It allows us to filter elements from an array based on a condition and returns only those that meet it. We create a boolean array from a condition and use it to select elements and can combine conditions with logical operators.*

*We can also use logical operators like & (AND), | (OR) and ~ (NOT) to combine conditions.*

In [51]:
arr = np.array([10, 15, 20, 25, 30])
print(arr[arr > 20])

[25 30]


In [52]:
print(arr[(arr > 10) & (arr < 30)])

[15 20 25]


### Erweitertes Indexing / *Fancy Indexing*

Wird auch als „Erweitertes Indexing“ bezeichnet, das es uns ermöglicht, auf Elemente eines Arrays mithilfe eines anderen Arrays oder einer Liste von Indizes zuzugreifen. Dadurch können mehrere Elemente gleichzeitig ausgewählt werden, auch wenn sie nicht nebeneinanderliegen, was es einfach macht, bestimmte Werte aus verschiedenen Positionen im Array auszuwählen.

---

*It is also known as Advanced Indexing which allows us access elements of an array by using another array or list of indices. This allows selecting multiple elements at once even if they are not next to each other which makes it easy to pick specific values from different positions in the array.*

In [53]:
indices = [0, 2, 4]
print(arr[indices])

[10 20 30]


#### Auslassungsoperator (...) / *Ellipsis (...) in Indexing*

Der Auslassungsoperator (...) kann verwendet werden, um alle Dimensionen auszuwählen, die nicht explizit angegeben sind. Dies ist bei mehrdimensionalen Arrays hilfreich, wenn wir nicht jede Dimension spezifizieren möchten.

---

*The ellipsis (...) can be used to select all dimensions which are not explicitly mentioned. This is helpful in multidimensional arrays when we don’t want to specify every dimension.*

In [61]:
cube = np.random.rand(4, 4, 4)
print(cube)
print("")
print(cube[..., 0]) # gets us every item of every dimension in collumn 0

[[[0.69536572 0.57260324 0.43805362 0.20851106]
  [0.54686435 0.08577106 0.11254043 0.92360454]
  [0.70048957 0.050541   0.14750618 0.65730727]
  [0.52979    0.28143806 0.05821588 0.23610804]]

 [[0.72656028 0.8096311  0.3345377  0.99110126]
  [0.54890171 0.91841862 0.08218118 0.62717426]
  [0.68028284 0.93071231 0.66534102 0.23196502]
  [0.061758   0.93863537 0.1903347  0.42390311]]

 [[0.94750496 0.7284803  0.01955583 0.22927255]
  [0.34101294 0.61237362 0.46210291 0.05686551]
  [0.65983211 0.60668231 0.25557576 0.77135336]
  [0.15803114 0.2600238  0.03105878 0.27513929]]

 [[0.18285957 0.38036131 0.92908791 0.77715038]
  [0.94802352 0.4015405  0.88278069 0.97799223]
  [0.65685559 0.78764736 0.80411892 0.84201691]
  [0.52597086 0.18086402 0.43041726 0.90449207]]]

[[0.69536572 0.54686435 0.70048957 0.52979   ]
 [0.72656028 0.54890171 0.68028284 0.061758  ]
 [0.94750496 0.34101294 0.65983211 0.15803114]
 [0.18285957 0.94802352 0.65685559 0.52597086]]


# Slicing Arrays

Es ermöglicht uns, einen Bereich von Elementen mithilfe des Formats start:stop:step zu extrahieren. Dies kann sowohl für 1D- als auch für mehrdimensionale Arrays durchgeführt werden, wodurch sich Bereiche von Elementen oder Teilmatrizen einfach auswählen lassen.

---

*It allows us to extract a range of elements using the format start:stop:step. This can be done for both 1D and multidimensional arrays which allows us to select ranges of elements or submatrices easily.*

In [62]:
arr = np.array([0, 1, 2, 3, 4, 5])

# slices the array starting at index 1 up to (but not including) index 4
print(arr[1:4])

[1 2 3]


In [67]:
a = np.arange(10)**3
print(a)
print(a[2:5])

[  0   1   8  27  64 125 216 343 512 729]
[ 8 27 64]


In [71]:
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
print(a[:5:2])
a[:10:2] = 1000
print(a)

[1000 1000 1000]
[1000    1 1000   27 1000  125 1000  343 1000  729]


In [72]:
# reversed a
print(a[::-1])

[ 729 1000  343 1000  125 1000   27 1000    1 1000]


In [73]:
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
9.999999999999998
6.999999999999999
9.999999999999998
8.999999999999998


Bei mehrdimensionalen Arrays kann das Slicing auf jede Dimension oder Achse separat angewendet werden, wodurch sich Teilmatrizen oder kleinere Datenblöcke extrahieren lassen. Pro Achse kann ein Index angegeben werden. Diese Indizes werden in einem durch Kommas getrennten Tupel angegeben.

---

*For multidimensional arrays, slicing can be applied to each dimension or axis separately which allows us to extract submatrices or smaller blocks of data. They can have one index per axis. These indices are given in a tuple separated by commas.*

In [78]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
matrix[1, 2]

np.int64(6)

In [77]:
# each row in the second column of matrix
print(matrix[0:5, 1])

# or
print(matrix[:, 1])

[2 5 8]
[2 5 8]


In [79]:
# each column in the second and third row of matrix
print(matrix[1:3, :])

# or
print(matrix[1:3])

[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]


In [80]:
# the last row. Equivalent to matrix[-1, :]
print(matrix[-1, :])

# or
print(matrix[-1])

[7 8 9]
[7 8 9]


In [81]:
print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]


In [88]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
print(c.shape)

(2, 2, 3)


In [83]:
print(c[1, ...])  # same as c[1, :, :] or c[1]

[[100 101 102]
 [110 112 113]]


In [84]:
print(c[..., 2])  # same as c[:, :, 2]

[[  2  13]
 [102 113]]


Das Iterieren über mehrdimensionale Arrays erfolgt entlang der ersten Achse:

---

*Iterating over multidimensional arrays is done with respect to the first axis:*

In [90]:
for row in matrix:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [91]:
for row in c:
    print(row)

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]


In [87]:
for element in matrix.flat:
    print(element)

1
2
3
4
5
6
7
8
9


### Aufgabe 1 / *Exercise 1:*
Extrahiere die erste Zeile und die letzte Spalte von:

---

*Extract first row and last column of:*

$\begin{bmatrix}5 & 10 & 15 \\20 & 25 & 30\end{bmatrix}$


In [115]:
np1 = np.array([[5,10,15],[20,25,30]])
print(npx)

print(npx[0])

[[ 5 10 15]
 [20 25 30]]
[[ 5 10 15]]


In [144]:
print(npx[:, -1])

[15 30]


### Aufgabe 2 / *Exercise 2:*

Gib die zweite und vierte Zeile aus / *Print the second and fourth row of*
$\begin{bmatrix}1 & 2 \\3 & 4 \\5 & 6 \\7 & 8 \end{bmatrix}$.

In [145]:
np2 = np.array([[1,2],[3,4],[5,6],[7,8]])
print(np2)

print(np2[1::2])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[3 4]
 [7 8]]


### Aufgabe 3 / *Exercise 3:*

Gegeben der folgenden Matrix:
* Extrahiere die diagonalen Elemente
* Extrahiere ungerade Zeilen und gerade Spalten
  
---

*Given the matrix below:*
- *Extract diagonal elements*
- *Extract Odd Rows and Even Columns*

$\begin{bmatrix}3 & 6 & 9 & 12 \\20 & 25 & 30 & 34\\ 76 & 43 & 89 & 57\\39 & 42 & 45 & 48\end{bmatrix}$

In [150]:
np3 = np.array([[3,6,9,12],[20,25,30,34],[76,43,89,57],[39,42,45,48]])
print(np3)
print(np.diag(np3))

print('')
print(np3[::2])
print('')
print(np3[:,::2])

print(np3[::2, 1::2])


[[ 3  6  9 12]
 [20 25 30 34]
 [76 43 89 57]
 [39 42 45 48]]
[ 3 25 89 48]

[[ 3  6  9 12]
 [76 43 89 57]]

[[ 3  9]
 [20 30]
 [76 89]
 [39 45]]
[[ 6 12]
 [43 57]]


### Aufgabe 4 / *Exercise 4:*

Erstelle ein $5\times5$ 2D-Array mit 1en am Rand und 0en innen.

---

*Create a $5\times5$ 2D array with 1s on the border and 0s inside.*

In [157]:
np4 = np.zeros((5,5))
print(np4)

# erste reihe
np4[0] = 1
# letzte reihe
np4[-1] = 1
# erste spalte
np4[:, 0] = 1
#letzte spalte
np4[:, -1] = 1
print('')
print(np4)
print()

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Ändern der Form eines Arrays / *Changing the shape of an array*

Ein Array hat eine Form, die durch die Anzahl der Elemente entlang jeder Achse bestimmt wird. Die Form eines Arrays kann mit verschiedenen Befehlen geändert werden. Zu beachten ist, dass die folgenden drei Befehle alle ein modifiziertes Array zurückgeben, das ursprüngliche Array jedoch nicht verändern:

---

*An array has a shape given by the number of elements along each axis. The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:*

In [158]:
a = np.array([[3, 7, 3, 4],
              [1, 4, 2, 2],
              [7, 2, 4, 9]])

print(a.shape)

(3, 4)


In [159]:
# returns the array, flattened
print(a.ravel())

[3 7 3 4 1 4 2 2 7 2 4 9]


In [160]:
# returns the array with a modified shape
print(a.reshape(6, 2))

[[3 7]
 [3 4]
 [1 4]
 [2 2]
 [7 2]
 [4 9]]


In [161]:
# prints a transpose of array a
print(a.T)
print(a.T.shape)

[[3 1 7]
 [7 4 2]
 [3 2 4]
 [4 2 9]]
(4, 3)


In [162]:
print(a.shape)

(3, 4)


Die Funktion `reshape` gibt ihr Argument mit geänderter Form zurück, während die Methode `ndarray.resize` das Array selbst verändert.

---

*The `reshape` function returns its argument with a modified shape, whereas the `ndarray.resize` method modifies the array itself.*

In [163]:
a.resize((2, 6))

print(a.shape)
print(a)

(2, 6)
[[3 7 3 4 1 4]
 [2 2 7 2 4 9]]


Wenn eine Dimension bei einer Umformung als -1 angegeben wird, werden die anderen Dimensionen automatisch berechnet:

---

*If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:*

In [176]:
a = np.array([[3, 7, 3, 4],
              [1, 4, 2, 2],
              [7, 2, 4, 9]])
# b= a.reshape(2, -1)
print(a)
print(a.shape)

print(b)
print(b.shape)

[[3 7 3 4]
 [1 4 2 2]
 [7 2 4 9]]
(3, 4)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
(5, 3)


In [177]:
a = np.arange(15)

In [178]:
b = a.reshape(3, 5)

print(a)
print(type(a))
print(f"Dimensions: {b.ndim}")
print(f"Shape: {b.shape}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
Dimensions: 2
Shape: (3, 5)


In [179]:
b = a.reshape(5, 3)

print(a)
print(type(a))
print(f"Dimensions: {b.ndim}")
print(f"Shape: {b.shape}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
Dimensions: 2
Shape: (5, 3)


In [181]:
b = a.reshape(2, 5)

print(a)
print(type(a))
print(f"Dimensions: {b.ndim}")
print(f"Shape: {b.shape}")

ValueError: cannot reshape array of size 15 into shape (2,5)

### Aufgabe / *Exercise*

Gegeben der folgenden Matrix:
* Formiere diese in ein 1D-Array um
* Wähle alle Elemente aus, die größer als 49 sind

---

*Given the matrix below:*
- *reshape into a 1-D array*
- *select all elements greater than 49*
  
$\begin{bmatrix}3 & 6 & 9 & 12 \\20 & 25 & 30 & 34\\ 76 & 43 & 89 & 57\\39 & 42 & 45 & 48\end{bmatrix}$

In [182]:
np4x4 = np.array()
ravel ->
np4x4[np4x4 > 49]



SyntaxError: invalid syntax (4030453181.py, line 2)

# Copies & views

Beim Arbeiten mit und Manipulieren von Arrays werden deren Daten manchmal in ein neues Array kopiert und manchmal nicht. Dies führt oft zu Verwirrung. Es gibt drei Fälle:

---

*When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion. There are three cases:*

### Keine Kopie / *No copy at all*

Einfache Zuweisungen erstellen keine Kopie der Objekte oder ihrer Daten.

---

*Simple assignments make no copy of objects or their data.*

In [212]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

# no new object is created
b = a
# a and b are two names for the same ndarray object
print(b is a)

True


### View / shallow copy

Verschiedene Array-Objekte können dieselben Daten gemeinsam nutzen. Die Methode view erstellt ein neues Array-Objekt, das auf dieselben Daten zugreift.

---

*Different array objects can share the same data. The `view` method creates a new array object that looks at the same data.*

In [213]:
c = a.view()
#this is a deep copy

In [214]:
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [215]:
print(c is a)

False


In [216]:
print(id(a))
print(id(c))

139059509400784
139059509402704


In [217]:
# c is a view of the data owned by a
print(c.base is a)

True


In [218]:
# a's shape doesn't change, reassigned c is still a view of a
c = c.reshape((2, 6))

print(f"Shape of a: {a.shape}")
print(f"Shape of c: {c.shape}")

Shape of a: (3, 4)
Shape of c: (2, 6)


In [219]:
print(a)
print(c)
print(id(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
139059509400784


In [220]:
c[0, 4] = 1234

print(a)
print(id(a))

[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
139059509400784


Das Slicing eines Arrays gibt eine Ansicht (View) darauf zurück:

---

*Slicing an array returns a view of it:*

In [221]:
s = a[:, 1:3]

# s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
s[:] = 10
print(a)

[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


### Deep copy

Die Methode copy erstellt eine vollständige Kopie des Arrays und seiner Daten.

---

*The copy method makes a complete copy of the array and its data.*

In [ ]:
d = a.copy()  # a new array object with new data is created
print(d is a)

In [ ]:
# d doesn't share anything with a; so the following would print false
print(d.base is a)

In [ ]:
d[0, 0] = 9999
print(a)

### Aufgabe / *Exercise*:

Für die folgenden Codeblöcke: Sage vorher, was die Ausgabe sein würde, ohne den Code auszuführen.
Führe dann den Code aus und versuche, die Ergebnisse zu interpretieren, falls sie von deinen Vorhersagen abweichen.

---

*For the following code blocks, predict what the output would be withoout running the code.
Then run the code and try to interpret the results if those are different from your predictions.*

A.
```
arr = np.array([10,20,30,40])
b = arr[[1,2]]

b[0] = 100

print(arr)
```

B.
```
arr = np.array([1,2,3,4])
b = arr[1:3]

b[0] = 100

print(arr)
```

C. Wie würden die Dimensionen des Ergebnisses aussehen?

---

C. *What would be the dimension of the result?*

```
arr = np.array([[1,2,3], [4,5,6]])
result = arr[1, :2]
print(result)

# Grundlegende mathematische Operationen in Numpy / *Basic mathematical operations in NumPy*

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

### Elementweise Operationen / *Element-wise Operations*

In NumPy erfolgt die Addition von zwei Arrays mithilfe der Funktion `np.add()`, wobei die entsprechenden Elemente der beiden Arrays zusammengezählt werden. Ebenso können wir zwei Arrays elementweise subtrahieren mit `np.subtract()` oder multiplizieren mit `np.multiply()`.

| Operation      | Symbol / Funktion | Beispielcode | Ausgabe          |
| -------------- | ----------------- | ------------ | ---------------- |
| Addition       | `+`               | `a + b`      | `[5 7 9]`        |
| Subtraktion    | `-`               | `a - b`      | `[-3 -3 -3]`     |
| Multiplikation | `*`               | `a * b`      | `[4 10 18]`      |
| Division       | `/`               | `a / b`      | `[0.25 0.4 0.5]` |
| Potenz         | `**`              | `a ** 2`     | `[1 4 9]`        |
| Modulo         | `%`               | `b % a`      | `[0 1 0]`        |
| Quadratwurzel  | `np.sqrt()`       | `np.sqrt(a)` | `[1. 1.41 1.73]` |
| Exponential    | `np.exp()`        | `np.exp(a)`  | `[e¹ e² e³]`     |
| Logarithmus    | `np.log()`        | `np.log(a)`  | `[0. 0.69 1.09]` |


---


In NumPy the addition of two arrays is done using the `np.add()` function and corresponding elements of two arrays are added together. Similarly, we can subtract two arrays element-wise using the `np.subtract()` or multiply using `np.multiply()`.

| Operation      | Symbol / Function | Example Code | Output           |
| -------------- | ----------------- | ------------ | ---------------- |
| Addition       | `+`               | `a + b`      | `[5 7 9]`        |
| Subtraction    | `-`               | `a - b`      | `[-3 -3 -3]`     |
| Multiplication | `*`               | `a * b`      | `[4 10 18]`      |
| Division       | `/`               | `a / b`      | `[0.25 0.4 0.5]` |
| Power          | `**`              | `a ** 2`     | `[1 4 9]`        |
| Modulus        | `%`               | `b % a`      | `[0 1 0]`        |
| Square Root    | `np.sqrt()`       | `np.sqrt(a)` | `[1. 1.41 1.73]` |
| Exponential    | `np.exp()`        | `np.exp(a)`  | `[e¹ e² e³]`     |
| Logarithm      | `np.log()`        | `np.log(a)`  | `[0. 0.69 1.09]` |


In [222]:
res = np.add(a, b)
print(res)

[[   0   20   20    6]
 [2468   20   20   14]
 [  16   20   20   22]]


Jedes Element in a wird zum entsprechenden Element in b addiert.

---

Each element in a is added to the corresponding element in b.

In [223]:
res = np.subtract(a, b)
print(res)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [224]:
res = np.multiply(a, b)
print(res)

[[      0     100     100       9]
 [1522756     100     100      49]
 [     64     100     100     121]]


Lasst uns das mit 2D-Arrays ausprobieren.

---

*Let us try with 2D arrays.*

In [225]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print(a + b)

[[ 6  8]
 [10 12]]


Auch hier erfolgen die Operationen elementweise. Beachten Sie jedoch, dass beide Arrays dieselbe Form haben.

---

*Again, operations happen element by element. But notice that both arrays are of the same shape.*

In [226]:
print(a.shape)
print(b.shape)

(2, 2)
(2, 2)


Was passiert, wenn die Arrays unterschiedliche Formen haben?

---

*What happens if the arrays are of different shape?*

In [227]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

In [229]:
print(a.shape)
print(b.shape)

(2, 3)
(3,)


Was wird bei a+b zurückgeben? Würde es zu einem Fehler führen?

---

*What do you think the `a+b` would return? would it go into error?*

In [231]:
print(a + b)

[[11 22 33]
 [14 25 36]]
[[11 22 33]
 [14 25 36]]


NumPy betrachtet dies nicht als Fehler – stattdessen wird es intelligent mithilfe von **Broadcasting** behandelt.

---

*NumPy does not treat this as an error — instead, it intelligently handles it using **broadcasting**.*

# Broadcasting

Einfach ausgedrückt ist Broadcasting NumPys Methode, Operationen auf Arrays unterschiedlicher Formen durchzuführen, ohne explizit Kopien zu erstellen oder Schleifen zu schreiben. Unter bestimmten Bedingungen wird das kleinere Array über das größere Array „broadcasted“, sodass sie kompatible Formen haben. Broadcasting bietet eine Möglichkeit, Array-Operationen zu vektorisieren, sodass die Schleifen in C anstelle von Python ausgeführt werden. Dabei werden unnötige Datenkopien vermieden, was in der Regel zu effizienten Implementierungen von Algorithmen führt. Es gibt jedoch Fälle, in denen Broadcasting eine schlechte Idee sein kann, da es zu ineffizienter Speichernutzung führt und die Berechnung verlangsamt.

---

*In simple terms, broadcasting is NumPy’s way of performing operations on arrays of different shapes without explicitly creating copies or writing loops. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting may be a bad idea because it leads to inefficient use of memory that slows computation.*

Beispiel 1: Broadcasting eines Skalars auf ein 1D-Array

---

*Example 1: Broadcasting a Scalar to a 1D Array*

In [234]:
# simplest example

a = np.array([1, 2, 3])
b = 5
print(a + b)

[6 7 8]


NumPy erstellt keine dreifache Kopie von b `([5, 5, 5])`. Stattdessen wird der Skalar während der Berechnung über das Array gebroadcastet.

---

*NumPy doesn’t create a copy of b repeated three times `([5, 5, 5])`. Instead, it broadcasts the scalar across the array during computation.*

### Generelle Regeln zu Broadcasting / *General broadcasting rules*

Beim Arbeiten mit zwei Arrays vergleicht NumPy deren Formen elementweise. Es beginnt mit der letzten (d. h. der ganz rechten) Dimension und arbeitet sich nach links vor. Zwei Dimensionen sind kompatibel, wenn
- sie gleich sind, oder
- eine von ihnen 1 ist.
  
Wenn diese Bedingungen nicht erfüllt sind, wird eine Ausnahme `ValueError: operands could not be broadcast together` ausgelöst, was darauf hinweist, dass die Arrays inkompatible Formen haben.

---

*When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when*
- *they are equal, or*
- *one of them is 1.*

*If these conditions are not met, a `ValueError: operands could not be broadcast together` exception is thrown, indicating that the arrays have incompatible shapes.*

Beispiel 2: Broadcasting eines 1D-Arrays auf ein 2D-Array

Dieses Beispiel zeigt, wie ein 1D-Array a1 zu einem 2D-Array a2 addiert wird. NumPy erweitert das 1D-Array automatisch entlang der Zeilen des 2D-Arrays, um die Addition elementweise durchzuführen.

---

*Example 2: Broadcasting a 1D Array to a 2D Array*

*This example shows how a 1D array a1 is added to a 2D array a2. NumPy automatically expands the 1D array along the rows of the 2D array to perform element-wise addition.*

In [235]:
import numpy as np

a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7, 9, 11]])
print(a + b)

[[ 3  7 11]
 [ 9 13 17]]


Erklärung / *Explanation*:

* a hat die Form (3,) und b hat die Form (2, 3).
* NumPy wiederholt a automatisch über beide Zeilen von b, sodass ihre Formen übereinstimmen.
* Dann werden die Elemente positionsweise addiert: $[1, 3, 5] + [2, 4, 6] = [3, 7, 11]$ und $[7, 9, 11] + [2, 4, 6] = [9, 13, 17]$

---

- *a has shape (3,) and b has shape (2, 3).*
- *NumPy automatically repeats a across both rows of b so their shapes match.*
- *Then it adds elements position-wise: $[1, 3, 5] + [2, 4, 6] = [3, 7, 11]$ and $[7, 9, 11] + [2, 4, 6] = [9, 13, 17]$*

Beispiel 3: Broadcasting bei bedingten Operationen

In diesem Beispiel wird jedes Alter im Array überprüft und mit `np.where()` "Erwachsen" oder "Minderjährig" zugewiesen.

---

*Example 3: Broadcasting in Conditional Operations*

*This example checks each age in the array and assigns "Adult" or "Minor" using `np.where()`.*

In [236]:
import numpy as np

ages = np.array([12, 24, 35, 45, 60, 72])
age_groups = np.array(["Adult", "Minor"])
res = np.where(ages > 18, age_groups[0], age_groups[1])
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


Erklärung / *Explanation*:

- ages > 18 erstellt ein Boolesches Array, indem jeder Wert auf einmal überprüft wird (Broadcasting).
- np.where() wählt "Adult" für True und "Minor" für False, ohne eine Schleife zu verwenden.
- Das Ergebnis ist ein Array, das jedes Alter korrekt kennzeichnet.

---

- *ages > 18 creates a Boolean array by checking every value at once (broadcasting).*
- `np.where()` *picks "Adult" for True and "Minor" for False without any loop.*
- *The result is an array labeling each age correctly.*

Beispiel 4 — Spalten-Broadcasting

Im folgenden Beispiel wird der Spaltenvektor b über die Spalten erweitert, sodass jede Zeile im größeren Array a einen anderen Wert erhält.

---

*Example 4 — Column Broadcasting*

*In the following example, the column vector `b` is expanded across columns so that each row in the larger array `a` receives a different value.*

In [237]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10],
              [20]])

print(a + b)

[[11 12 13]
 [24 25 26]]


Erklärung / *Explanation*:

- Was passiert / *what happens*:
    ```
    [1 2 3]  +  [10]
    [4 5 6]  +  [20]
    ```
    
- Ergebnis / *result*
    ```
    [[11 12 13]
     [24 25 26]]
    ```

Beispiel 5 - Ungültiges Broadcasting

---

*Example 5 - Invalid Broadcasting*

In [238]:
a = np.array([1,2,3])   # shape (3,)
b = np.array([1, 2])    # shape (2,)
print(a + b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

Erklärung: von rechts 3 vs 2 → ❌ nicht gleich und nicht 1

---

*Explanation: from right `3 vs 2` → ❌ not equal and not 1*

# Aufgaben / *Exercises*

### Aufgabe 1 / *Exercise 1*

Es sind die Gehälter von 5 Personen für die Jahre 2023 und 2024 gegeben.

```
salary_2023 = np.array([3000, 4000, 5000, 1200, 975])
salary_2024 = np.array([3200, 4200, 5500, 1800, 1100])
```

Berechne:
- Gehaltserhöhung
- prozentuale Erhöhung

---

*You are given salaries of 5 people for year 2023 and 2024.*
```
salary_2023 = np.array([3000, 4000, 5000, 1200, 975])
salary_2024 = np.array([3200, 4200, 5500, 1800, 1100])
```

*Compute:*
- *salary increase*
- *percentage increase*

### Aufgabe 2 / *Exercise 2*

Es sind die Bestandsdaten eines Geschäfts für heute gegeben.
```
stock = np.array([[10, 20, 30],
                  [5, 15, 25]])

sold = np.array([[2, 3, 4],
                 [1, 2, 3]])
```

* Berechne den verbleibenden Lagerbestand
* Finde Artikel mit einem Bestand < 10
  
---

*You are given the inventory data of a store for today:*
```
stock = np.array([[10, 20, 30],
                  [5, 15, 25]])

sold = np.array([[2, 3, 4],
                 [1, 2, 3]])
```
- *Compute remaining stock*
- *Find items with stock < 10*


In [ ]:
# add your solution here

### Aufgabe 3 / *Exercise 3*

```
marks = np.array([[70, 80, 90],
                  [60, 75, 85]])

bonus = np.array([5, 10, 15])
```

Aufgaben:
* Füge Bonus zu den Noten hinzu
* Berechne neue Durchschnitte
* Finde Studenten mit einem Durchschnitt > 80

---

*Tasks*:
- *add bonus to marks*
- *compute new averages*
- *find students with average $> 80$*

In [ ]:
# add your solution here

# Häufig verwendete nützliche NumPy-Funktionen / *Common Useful Numpy Functions*

`arr = np.array([10, 20, 30, 40])`

| Funktion      | Beschreibung           | Beispielcode           | Ausgabe           |
| ------------- | ---------------------- | ---------------------- | ----------------- |
| `np.where()`  | Bedingte Auswahl       | `np.where(arr > 20)`   | `(array([2,3]),)` |
| `np.argmax()` | Index des Maximalwerts | `np.argmax(arr)`       | `3`               |
| `np.argmin()` | Index des Minimalwerts | `np.argmin(arr)`       | `0`               |
| `np.unique()` | Einzigartige Elemente  | `np.unique([1,2,2,3])` | `[1 2 3]`         |
| `np.sort()`   | Array sortieren        | `np.sort(arr)`         | `[10 20 30 40]`   |
| `np.clip()`   | Werte begrenzen        | `np.clip(arr, 15, 35)` | `[15 20 30 35]`   |


---

`arr = np.array([10, 20, 30, 40])`

| Function      | Description           | Example Code           | Output            |
| ------------- | --------------------- | ---------------------- | ----------------- |
| `np.where()`  | Conditional selection | `np.where(arr > 20)`   | `(array([2,3]),)` |
| `np.argmax()` | Index of max value    | `np.argmax(arr)`       | `3`               |
| `np.argmin()` | Index of min value    | `np.argmin(arr)`       | `0`               |
| `np.unique()` | Unique elements       | `np.unique([1,2,2,3])` | `[1 2 3]`         |
| `np.sort()`   | Sort array            | `np.sort(arr)`         | `[10 20 30 40]`   |
| `np.clip()`   | Limit values          | `np.clip(arr, 15, 35)` | `[15 20 30 35]`   |


# Aufgaben / *Exercises*

### Aufgabe 1 / *Exercise 1*

Finde die Positionen, an denen die Elemente der Arrays a und b übereinstimmen:

---

*Get the positions where elements of array a and b match:*
```
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])

In [ ]:
# add your solution here

### Aufgabe 2 / *Exercise 2*

`marks = np.array([50, 75, 90, 60, 85])`

* Finde den Index des Schülers/der Schülerin mit den höchsten und niedrigsten Noten
* Zähle die Schüler mit Noten unter 60 und über 80

---

- *Find student index with highest and lowest marks*
- *Count students with marks less than 60 and greater than 80*

In [ ]:
# add your solution here

# Aggregationsfunktionen in NumPy / *Aggregation Functions in NumPy*


Aggregationsfunktionen werden verwendet, um mehrere Werte in einem Array zu einer einzigen Ergebnisgröße zusammenzufassen oder zu kombinieren. Diese Funktionen führen Operationen wie die Berechnung der Summe, des Mittelwerts, des Minimums oder Maximums der Elemente in einem NumPy-Array durch.

Aggregation ist sehr nützlich in der Datenanalyse und Statistik, wo oft Gesamtmaße aus einem Datensatz berechnet werden müssen.

##### Häufige Aggregationsfunktionen

| Funktion    | Beschreibung         |
| ----------- | -------------------- |
| `np.sum()`  | Summe aller Elemente |
| `np.mean()` | Durchschnittswert    |
| `np.max()`  | Maximalwert          |
| `np.min()`  | Minimalwert          |
| `np.std()`  | Standardabweichung   |


---

*Aggregation functions are used to summarize or combine multiple values in an array into a single result. These functions perform operations such as finding the sum, mean, minimum, or maximum of the elements in a NumPy array.*

*Aggregation is very useful in data analysis and statistics, where we often need to compute overall measures from a dataset.*

##### Common Aggregation Functions

| Function    | Description         |
| ----------- | ------------------- |
| `np.sum()`  | Sum of all elements |
| `np.mean()` | Average value       |
| `np.max()`  | Maximum value       |
| `np.min()`  | Minimum value       |
| `np.std()`  | Standard deviation  |

Optionally, you can specify an axis that specifies the direction along which an operation is performed. `axis=0` operates down columns, while `axis=1` operates across rows.

In [239]:
arr = np.array([10, 20, 30, 40])

print(np.sum(arr))   # 100
print(np.mean(arr))  # 25
print(np.max(arr))   # 40
print(np.min(arr))   # 10

100
25.0
40
10


In [240]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(np.sum(arr))

21


In [241]:
print(np.sum(arr, axis=1))

[ 6 15]


Erklärung / *Explanation*:
- Row 1 → 1 + 2 + 3 = 6
- Row 2 → 4 + 5 + 6 = 15

In [242]:
print(np.sum(arr, axis=0))

[5 7 9]


Erklärung / *Explanation*:
- Column 1 → 1 + 4 = 5
- Column 2 → 2 + 5 = 7
- Column 3 → 3 + 6 = 9

| Achse    | Bedeutung                                        |
| -------- | ------------------------------------------------ |
| `axis=0` | Operation **entlang der Spalten (spaltenweise)** |
| `axis=1` | Operation **entlang der Zeilen (zeilenweise)**   |


| Axis     | Meaning                               |
| -------- | ------------------------------------- |
| `axis=0` | operate **down rows (column-wise)**   |
| `axis=1` | operate **across columns (row-wise)** |


# Aufgabe / *Exercise*

Das Folgende ist eine Aufzeichnung der täglichen Ausgaben in der letzten Woche.

| Tag        | Essen (€) | Transport (€) | Unterhaltung (€) |
| ---------- | --------- | ------------- | ---------------- |
| Montag     | 20        | 10            | 15               |
| Dienstag   | 25        | 12            | 18               |
| Mittwoch   | 22        | 9             | 20               |
| Donnerstag | 30        | 15            | 25               |
| Freitag    | 28        | 14            | 22               |
| Samstag    | 35        | 18            | 30               |
| Sonntag    | 40        | 20            | 35               |

Berechne:
* Gesamtausgaben pro Tag
* Gesamtausgaben pro Kategorie
* Durchschnittliche tägliche Ausgaben
* Der Tag mit den höchsten Ausgaben
* Finde alle Ausgaben über 20 €
* Extrahiere die Transportausgaben

---

*The following is a record of your daily expenses last week.*

| Day       | Food (€) | Transport (€) | Entertainment (€) |
| --------- | -------- | ------------- | ----------------- |
| Monday    | 20       | 10            | 15                |
| Tuesday   | 25       | 12            | 18                |
| Wednesday | 22       | 9             | 20                |
| Thursday  | 30       | 15            | 25                |
| Friday    | 28       | 14            | 22                |
| Saturday  | 35       | 18            | 30                |
| Sunday    | 40       | 20            | 35                |

*Calculate:*
1. *Total expenses per day*
2. *Total expenses per category*
3. *Average daily expenses*
4. *The day with highest spending*
5. *Find all expenses greater than 20€*
6. *Extract transport expenses*

In [ ]:
# add your solution here

#### NumPy ufuncs oder universelle Funktionen / *NumPy ufuncs or universal functions*

NumPy ufuncs (universelle Funktionen) sind schnelle, vektorisierte Funktionen, die elementweise Operationen auf NumPy-Arrays ausführen. Sie sind hoch optimiert und unterstützen Funktionen wie Broadcasting und automatische Typbehandlung. NumPy enthält viele ufuncs für Arithmetik, Trigonometrie, Statistik usw., und sie führen Operationen sehr schnell aus, da sie in optimiertem C-Code implementiert sind.

##### Warum sollten wir ufuncs verwenden?
- Schnelle vektorisierte Operationen: Ufuncs wenden Berechnungen auf ganze Arrays gleichzeitig an, was sie wesentlich schneller als Python-Schleifen macht.
- Automatisches Broadcasting und Typbehandlung: Sie passen Array-Formen automatisch an und führen intern Datentypkonvertierungen durch, wodurch Fehler reduziert werden.
- Saubererer und effizienterer Code: Sie vereinfachen komplexe numerische Aufgaben zu kurzem, lesbarem Code, der gut auf großen Datensätzen skaliert.

---

*NumPy ufuncs (universal functions) are fast, vectorized functions that perform element-wise operations on NumPy arrays. They are highly optimized and support features like broadcasting and automatic type handling. NumPy includes many ufuncs for arithmetic, trigonometry, statistics, etc, and they execute operations very fast because they are implemented in optimized C code.*

##### *Why use ufuncs?*
- *Fast vectorized operations: Ufuncs apply calculations to entire arrays at once, making them much faster than Python loops.*
- *Automatic broadcasting and type handling: They adjust array shapes automatically and handle datatype conversion internally, reducing errors.*
- *Cleaner and more efficient code: They simplify complex numerical tasks into short, readable code that scales well on large datasets.*

##### Beispiele für universelle Funktionen in Python / *Examples Universal Functions in Numpy*

```
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
```

| Funktion        | Typ   | Beschreibung                | Beispielcode        | Ausgabe               |
| --------------- | ----- | --------------------------- | ------------------- | --------------------- |
| `np.add()`      | ufunc | Elementweise Addition       | `np.add(a, b)`      | `[5 7 9]`             |
| `np.subtract()` | ufunc | Elementweise Subtraktion    | `np.subtract(a, b)` | `[-3 -3 -3]`          |
| `np.multiply()` | ufunc | Elementweise Multiplikation | `np.multiply(a, b)` | `[4 10 18]`           |
| `np.divide()`   | ufunc | Elementweise Division       | `np.divide(a, b)`   | `[0.25 0.4 0.5]`      |
| `np.power()`    | ufunc | Elemente potenzieren        | `np.power(a, b)`    | `[1^4, 2^5, 3^6]`     |
| `np.mod()`      | ufunc | Elementweiser Restwert      | `np.mod(a, b)`      | `[1 2 3]`             |
| `np.maximum()`  | ufunc | Elementweises Maximum       | `np.maximum(a, b)`  | `[4 5 6]`             |
| `np.minimum()`  | ufunc | Elementweises Minimum       | `np.minimum(a, b)`  | `[1 2 3]`             |
| `np.greater()`  | ufunc | Elementweise Vergleich      | `np.greater(a, b)`  | `[False False False]` |
| `np.equal()`    | ufunc | Elementweise Gleichheit     | `np.equal(a, b)`    | `[False False False]` |



---

| Function        | Type  | Description                 | Example Code        | Output                |
| --------------- | ----- | --------------------------- | ------------------- | --------------------- |
| `np.add()`      | ufunc | Element-wise addition       | `np.add(a, b)`      | `[5 7 9]`             |
| `np.subtract()` | ufunc | Element-wise subtraction    | `np.subtract(a, b)` | `[-3 -3 -3]`          |
| `np.multiply()` | ufunc | Element-wise multiplication | `np.multiply(a, b)` | `[4 10 18]`           |
| `np.divide()`   | ufunc | Element-wise division       | `np.divide(a, b)`   | `[0.25 0.4 0.5]`      |
| `np.power()`    | ufunc | Raise elements to powers    | `np.power(a, b)`    | `[1^4, 2^5, 3^6]`     |
| `np.mod()`      | ufunc | Element-wise remainder      | `np.mod(a, b)`      | `[1 2 3]`             |
| `np.maximum()`  | ufunc | Element-wise max            | `np.maximum(a, b)`  | `[4 5 6]`             |
| `np.minimum()`  | ufunc | Element-wise min            | `np.minimum(a, b)`  | `[1 2 3]`             |
| `np.greater()`  | ufunc | Element-wise comparison     | `np.greater(a, b)`  | `[False False False]` |
| `np.equal()`    | ufunc | Element-wise equality       | `np.equal(a, b)`    | `[False False False]` |
